// Curriculum data for /kurikulum.
// Three tiers — Brand Lab (sequential), Playmaker Room (thematic), War Room (tactical).
// Each module: { n, title, sub, tags[], dur, free?, cs?, del, subs[] }

export const BL_PHASES = [
  {
    n: '01',
    title: 'Fondasi Bisnis',
    modules: [
      {
        n: '01',
        free: true,
        title: 'Kenapa Brand Lo Belum Laku',
        sub: 'Diagnosa jujur sebelum bakar duit',
        tags: ['fundamental'],
        dur: '5 video · 60 mnt',
        del: 'Brand Diagnostic Sheet',
        subs: [
          '4 alasan utama brand pemula stuck di bawah 10jt/bln',
          'Kategori produk vs ekspektasi revenue: Fashion / Beauty / F&B / Home — angka real',
          'Validasi demand via Tokpi/Compas/Kalodata (versi gratis)',
          'Kompetitor mapping: 5 brand benchmark di tier yang sama',
          'Output wajib: 1-pager Brand Diagnostic sebelum lanjut ke Modul 2',
        ],
      },
      {
        n: '02',
        free: true,
        title: 'Bangun Tim yang Benar: Siapa, Kapan, Berapa',
        sub: 'Peta tim ideal dari 0 sampai 500jt/bln — dan siapa yang jangan di-hire duluan',
        tags: ['ops', 'team', 'fundamental'],
        dur: '4 video · 55 mnt',
        del: 'Team Structure Blueprint + Hire Sequencing Roadmap 2026',
        subs: [
          'Peta tim per revenue stage: solo → 3 orang → 6 orang → 10 orang. Revenue threshold dan trigger wajib hire di tiap stage — bukan feeling, pakai angka',
          'Fungsi yang bisa outsource di awal: foto produk, live host, content creator lepas — bedain mana yang core (jangan outsource) vs non-core (boleh lepas)',
          'Hire pertama yang salah = yang paling sering bikin founder boncos. Data dari 100+ brand: admin CS harus masuk sebelum packer, bukan setelah',
          'Tim yang tidak perlu dari hari pertama: CMO, brand strategist full-time, in-house designer — timing yang benar untuk hire peran strategis',
          'Cost benchmark 2026 per role: Admin CS Rp 3–5jt, Packer/Ops Rp 3.5–5jt, Content Creator Rp 5–10jt, Live Host Rp 4–8jt — Jabodetabek vs daerah',
          'Remote vs on-site untuk brand e-commerce stage 0–500jt: ops dan packing butuh on-site, CS dan konten bisa remote — model hybrid yang terbukti efisien',
        ],
      },
      {
        n: '03',
        title: 'HPP Real, Bukan HPP Asumsi',
        sub: 'Semua hidden cost + break-even ROAS per SKU',
        tags: ['fundamental'],
        dur: '4 video · 50 mnt',
        del: 'HPP & Break-Even Calculator',
        subs: [
          'Komponen HPP yang sering kelewat: packaging, kurir, fee MP, retur, free ongkir share',
          'Template HPP per kategori: Fashion / Beauty / F&B / Home / Electronics',
          'Rumus break-even ROAS dengan contoh angka konkret',
          'Skema harga: normal vs flash sale vs live-only vs bundling',
          'Floor price: harga terendah yang masih profit di setiap channel',
        ],
      },
      {
        n: '04',
        free: true,
        title: 'Legal & Compliance Beres 7 Hari',
        sub: 'NIB, BPOM, Halal, HKI — urutan & timeline real',
        tags: ['fundamental', 'ops'],
        dur: '4 video · 45 mnt',
        del: 'Legal Readiness Checklist',
        subs: [
          'NIB, NPWP, izin PIRT/BPOM/Halal: urutan dan timeline yang real (bukan teori)',
          'Klaim produk yang aman vs yang BPOM ban — contoh nyata',
          'HKI & daftar merek di DJKI: kapan wajib, biayanya berapa',
          'Compliance untuk produk impor: SNI, LARTAS, sertifikasi',
          'Daftar pelanggaran kategorial yang bikin listing takedown di MP',
        ],
      },
      {
        n: '05',
        title: 'Setup Toko Shopee: A–Z',
        sub: 'Dari daftar sampai voucher pertama nyala',
        tags: ['teknis'],
        dur: '6 video · 70 mnt',
        del: 'Shopee Store Setup Checklist 2026',
        subs: [
          'Daftar Shopee + dokumen yang sering miss: NPWP toko vs pribadi',
          'Branding toko: banner, profile, kategori yang algoritma reward',
          'Setup ongkir & subsidi: free ongkir XTRA, gratis ongkir reguler',
          'Voucher logic: urutan voucher yang optimal untuk pemula',
          'Roadmap progresi: Star Seller → Preferred → Mall',
          'Setting fitur: chat auto-reply, FAQ produk, varian produk',
        ],
      },
      {
        n: '06',
        title: 'Setup Toko TikTok Shop: A–Z',
        sub: 'Dari daftar sampai GMV Max siap aktif',
        tags: ['teknis'],
        dur: '6 video · 75 mnt',
        del: 'TikTok Shop Setup SOP 2026',
        subs: [
          'Daftar TikTok Shop pasca merger Tokopedia via Seller Center (alur terbaru)',
          'Hubungkan akun TikTok personal/bisnis ke toko — step yang sering gagal',
          'Komisi 4–6% dinamis per kategori (berlaku Juni 2025) — efek ke pricing lo',
          'Setting Affiliate Plan: open vs targeted, komisi benchmark 10–15%',
          'Compliance konten komersial: label, klaim, konten yang dilarang',
          'Cara aktifkan keranjang kuning di video & live',
        ],
      },
    ],
  },
  {
    n: '02',
    title: 'Listing, Foto & Konten',
    modules: [
      {
        n: '07',
        title: 'Foto Produk Modal HP yang Convert',
        sub: 'Studio < Rp 500rb yang bikin orang beli',
        tags: ['teknis'],
        dur: '5 video · 60 mnt',
        del: 'Photo Kit + Preset Lightroom (5 kategori)',
        subs: [
          'Setup studio HP: ring light vs softbox, backdrop sesuai warna brand',
          '5 angle wajib + 1 lifestyle shot per kategori: Fashion/Beauty/F&B/Home',
          'Main image rules yang algoritma Shopee/TikTok Shop reward',
          'Edit modal Lightroom Mobile/Snapseed — preset gratis siap pakai',
          'A/B test foto utama untuk identifikasi mana yang CTR lebih tinggi',
        ],
      },
      {
        n: '08',
        title: 'Listing yang Searchable & Convert',
        sub: 'Judul, deskripsi, keyword — formula per platform',
        tags: ['teknis'],
        dur: '6 video · 75 mnt',
        del: 'Listing Builder Sheet',
        subs: [
          'Formula judul Shopee: keyword utama + benefit + diferensiator + variant',
          'Formula judul TikTok Shop: berbeda dari Shopee — fokus klaim hasil + urgency',
          'Description framework: komposisi — cara pakai — klaim legal — garansi — FAQ',
          'Riset keyword gratis: Shopee suggest + Tokpi/Compas basic',
          'Variant strategy: kapan pakai, kapan jangan — efek ke ranking',
          'Cross-listing 4 MP tanpa konflik kata kunci dan harga',
        ],
      },
      {
        n: '09',
        title: 'Video Product Demo 60 Detik yang FYP',
        sub: '30 video dalam 30 hari — struktur, edit, posting',
        tags: ['teknis', 'growth'],
        dur: '7 video · 85 mnt',
        del: 'Video Script Bank — 50 hook + 10 skrip',
        subs: [
          'Anatomi video viral: Hook 3 detik → Pain Point → Demo → Before/After → CTA keranjang',
          '12 hook template yang masih perform di 2026 — dengan contoh video referensi',
          'Recording setup minimal: HP + tripod + mic eksternal < Rp 300rb',
          'Edit di CapCut: cutting cepat, caption auto, sound viral, CapCut AI',
          'Posting schedule: 1–2 video/hari selama 30 hari pertama — kenapa ini wajib',
          'Kalau views stuck 100–500: checklist iterasi yang harus dicek',
        ],
      },
      {
        n: '10',
        title: '30 Review Bintang 5 di Bulan Pertama',
        sub: 'Cara legal dapat ulasan asli bervolume',
        tags: ['growth', 'ops'],
        dur: '4 video · 50 mnt',
        del: 'Seeding Sheet + WA Message Template',
        subs: [
          'Friend order: framework minta teman/keluarga jadi review awal (Sekolah Seller style)',
          'Sample seeding ke 30 nano-influencer dengan budget < Rp 3jt',
          'Follow-up message setelah delivery: template WA yang dorong review produk',
          'Insentif review: voucher next-purchase, refund partial untuk review video',
          'Risk management: fake review yang Shopee/TikTok bisa detect — cara hindari',
        ],
      },
      {
        n: '11',
        title: 'Hero Product: Pilih 1 SKU yang Lo Goreng',
        sub: 'Fokus = leverage. Scatter = mati',
        tags: ['fundamental', 'growth'],
        dur: '4 video · 50 mnt',
        del: 'Hero Product Selector Matrix',
        subs: [
          'Kriteria Hero Product dengan angka: margin 40%+, demand bulanan, repeat rate',
          'Cara pilih hero dari katalog yang ada: matriks margin × demand',
          'Hero pricing psychology: range Rp 49rb / 99rb / 149rb',
          'Bundle strategy: hero + companion SKU untuk naikin AOV 30–50%',
          'Hero positioning: produk lo = solusi apa dalam 1 kalimat',
        ],
      },
      {
        n: '12',
        title: 'Copywriting Jualan — Caption, Chat, Deskripsi',
        sub: 'Convert tanpa "sok marketer"',
        tags: ['teknis', 'growth'],
        dur: '5 video · 55 mnt',
        del: 'Copy Bank — 100 caption + 30 chat template',
        subs: [
          '4 formula copywriting yang work untuk e-commerce Indonesia: PAS, AIDA, FAB, Before-After',
          'Caption TikTok yang push klik keranjang kuning',
          'Caption Shopee yang push add-to-cart tanpa terdengar memaksa',
          'Chat auto-reply yang turn inquiry jadi checkout',
          'Anti-cringe list: kalimat motivasional, over-promise, dan religious-mixing yang harus dihindari',
        ],
      },
    ],
  },
  {
    n: '03',
    title: 'Traffic & Sales',
    modules: [
      {
        n: '13',
        free: true,
        title: 'Algoritma TikTok Shop & Shopee untuk Toko Baru',
        sub: 'Signal yang harus lo feed di 60 hari pertama',
        tags: ['teknis', 'growth'],
        dur: '4 video · 50 mnt',
        del: '60-Day Algorithm Boost Roadmap',
        subs: [
          'TikTok Shop: initial engagement signal kritis di 1–2 jam pertama setelah posting',
          'Shopee algoritma: trust score, response rate, fulfillment rate — cara naikin',
          'Aktivitas wajib harian toko baru agar tidak tenggelam di algoritma',
          'Patokan angka kapan algoritma mulai promote toko baru',
          'Common mistake yang reset algoritma: ganti nama, ubah niche, vakum 7 hari',
        ],
      },
      {
        n: '14',
        title: 'Shopee Ads dari Rp 50rb/Hari',
        sub: 'ROAS 3–5x dalam 14 hari',
        tags: ['teknis', 'growth'],
        dur: '5 video · 65 mnt',
        del: 'Shopee Ads Daily Tracker',
        subs: [
          'Jenis Shopee Ads: Pencarian Produk vs Toko vs Discovery — kapan pakai mana',
          'Setup kampanye pertama: keyword broad/exact, bid manual vs otomatis',
          'Cara baca laporan: CTR, CIR, ROAS, GMV per Klik',
          'Optimasi minggu 1–2: kapan tambah keyword, kapan kurangi bid',
          'Boncos protection: batas spend harian + alarm ROAS minimum yang harus di-set',
        ],
      },
      {
        n: '15',
        title: 'TikTok Ads Manager: Ekosistem, Search Ads & Creative Setup',
        sub: 'Seller Center vs Ads Manager vs Business Center — 3 pintu yang beda fungsinya',
        tags: ['teknis', 'ads'],
        dur: '5 video · 65 mnt',
        del: 'TikTok Account Structure Checklist + Search Ads Keyword Starter Pack',
        subs: [
          'Peta ekosistem TikTok ads: Seller Center (entry) → Ads Manager (control room) → Business Center (enterprise) — mana yang dipakai kapan dan bagaimana ketiganya terhubung',
          'Primary Ad Account rules: 1 toko = 1 primary account. Ganti sembarangan = semua GMV Max aktif auto-pause. Ini kesalahan paling mahal yang sering tidak disadari pemula',
          'TikTok Search Ads: keyword intent targeting yang masih tersedia terpisah dari GMV Max — kapan pakai Search Ads vs GMV Max, cara setup, dan bid benchmark per kategori',
          'Creative asset wajib sebelum GMV Max: minimum 5 video organik + 10 affiliate posts authorized. Tanpa ini algoritma tidak punya material untuk optimize dan boncos lebih besar',
          'Spark Ads authorization: cara approve konten organik dan kreator menjadi asset GMV Max — step by step dari Seller Center',
          'Common setup error pemula: salah connect Business Center, multiple primary accounts, tidak authorize affiliate content sebelum launch — dan cara benerin',
        ],
      },
      {
        n: '16',
        title: 'GMV Max: Setup, Target ROI, Risk Control',
        sub: 'Default TikTok Ads per Juli 2025 — wajib kuasai',
        tags: ['teknis', 'growth'],
        dur: '7 video · 95 mnt',
        del: 'GMV Max Setup Sheet + Target ROI Calculator',
        subs: [
          'Product GMV Max vs LIVE GMV Max: kapan pakai yang mana',
          'Setup Primary Ad Account: 1 toko = 1 ad account (aturan baru)',
          'Cara hitung Target ROI minimum: rumus break-even + safety margin',
          'Asset wajib sebelum launch: minimal 3–5 video kreatif + affiliate posts',
          'Scale up rule disiplin: maks +20% budget per 2 hari',
          'Kapan jeda kampanye, kapan double-down — decision tree',
          'Integrasi organik + affiliate + paid untuk atribusi akurat',
        ],
      },
      {
        n: '17',
        title: 'Live Pertama: HP, Studio Mini, Host Sendiri',
        sub: '3–4x/minggu dengan konversi >5%',
        tags: ['teknis', 'growth'],
        dur: '6 video · 80 mnt',
        del: 'Live Script 60 Mnt + Studio Setup List',
        subs: [
          'Setup live modal HP: lighting, mic, backdrop, layout produk di frame',
          'Skrip 60 menit pertama: pembukaan → demo produk → urgensi → closing',
          'Pre-heat live: notif 1 jam sebelum, post video teaser, broadcast WA',
          'Host pertama = lo sendiri: cara latih on-cam confidence tanpa cringe',
          'Interaktivitas: balas komen, mention nama penonton, kuis untuk retention',
          'Voucher live-only: cara setting flash sale di Shopee Live & TikTok Live',
        ],
      },
      {
        n: '18',
        title: 'Affiliate Pertama: Brief & Onboard 100 Affiliator',
        sub: '30 affiliator produktif dalam 60 hari',
        tags: ['growth', 'ops'],
        dur: '6 video · 75 mnt',
        del: 'Affiliate Brief Template + Seeding Tracker',
        subs: [
          'Setting Affiliate Plan TikTok Shop: open vs targeted, komisi 10–15% benchmark',
          'Setting Affiliate Shopee: sample seeding via DM, kode promo unik per kreator',
          'Brief affiliator: angle konten yang boleh, klaim yang safe, contoh hook',
          'Sample seeding logistics: budgeting, packaging untuk kreator, SOP follow-up',
          'Komunitas affiliator: grup WA, weekly briefing, leaderboard sederhana',
          'Filter & remove affiliator toxic: spam, klaim ilegal, leakage harga',
        ],
      },
      {
        n: '19',
        title: 'Promo, Voucher, Flash Sale — Yang Beneran vs Yang Bakar Margin',
        sub: 'Ikut kampanye dengan logic angka, bukan FOMO',
        tags: ['growth', 'fundamental'],
        dur: '4 video · 50 mnt',
        del: 'Promo P&L Calculator',
        subs: [
          'Jenis voucher Shopee/TikTok: ongkir, cashback, diskon — biaya ditanggung siapa',
          'Kampanye tanggal kembar (9.9, 10.10, 11.11): cost vs uplift yang real',
          'Flash sale strategy: rugi sedikit untuk traffic vs profit hilang sama sekali',
          '"Beli 2 gratis 1" vs "diskon 20%" — hitungan margin yang jujur',
          'Voucher live-only: cara kunci urgensi tanpa rusak price image normal',
        ],
      },
      {
        n: '20',
        title: 'Cross-Platform: Shopee vs TikTok — Mana Dulu, Kapan Dua-duanya',
        sub: 'Sequencing yang tidak overlap budget & konflik harga',
        tags: ['fundamental', 'growth'],
        dur: '4 video · 55 mnt',
        del: 'Channel Strategy Decision Tree',
        subs: [
          'Karakter platform: Shopee niat-beli, TikTok impulsif-beli — implikasi ke strategi',
          'Produk yang cocok di TikTok (visual/demo-heavy) vs Shopee (search-heavy)',
          'Sequencing options: TikTok dulu → Shopee, atau paralel — kapan mana',
          'Pricing: kapan harga sama, kapan beda — risk perang harga internal',
          'Sync inventory antar platform: BigSeller, Mekari Desty, Everpro',
        ],
      },
      {
        n: '21',
        title: 'CPAS Intro: Meta Ads × Shopee × Tokopedia untuk Brand yang Mau Scale',
        sub: 'Bridge antara Meta audience dan marketplace checkout — cara brand 300jt+ pakai diam-diam',
        tags: ['ads', 'cpas'],
        dur: '6 video · 80 mnt',
        del: 'CPAS Starter Checklist + Catalog Hygiene Template + Retargeting Audience Tier Sheet',
        subs: [
          'Mekanisme CPAS: Meta ads (FB/IG) → klik → landing langsung ke listing marketplace → checkout. Kenapa powerful: 70%+ transaksi online Indonesia ada di marketplace, bukan website — CPAS menjembatani gap ini',
          'Tokopedia CPAS: open untuk semua seller tanpa whitelist. Brand Portal → Marketing Solutions → CPAS Onboarding. UTM parameter CPAS-XXXX wajib per listing. Mulai dari sini dulu',
          'Shopee CPAS whitelist: email marketing.solutions.id@shopee.com dengan subject "CPAS Shopee Request-[Nama Brand]". Approval 7–14 hari kerja. Apply paralel saat setup Tokopedia',
          'Catalog hygiene wajib sebelum CPAS aktif: pricing konsisten dengan listing MP, image tanpa text overlay >20%, judul match listing, stok real-time sync — ini reject reason paling umum',
          'Strategi pertama yang benar: mulai dari retargeting dulu (cart abandoner 7 hari, product viewer 14 hari) bukan prospecting. Budget minimum Rp200–500rb/hari per ad set agar Meta algorithm bisa optimize',
          'Warning penting: CPAS Shopee whitelist-only — brand yang belum disetujui tidak bisa akses catalog segment. Jangan skip step ini. Tokopedia lebih lenient untuk mulai sambil tunggu approval Shopee',
        ],
      },
    ],
  },
  {
    n: '04',
    title: 'Ops & Skala ke 100jt',
    modules: [
      {
        n: '22',
        title: 'Inventory Management: Dari Manual ke Sistem',
        sub: 'Stok real-time, reorder point, expiry alert',
        tags: ['ops'],
        dur: '4 video · 50 mnt',
        del: 'Inventory Tracker + Reorder Point Calculator',
        subs: [
          'Klasifikasi SKU: A (80% revenue), B, C — beda treatment dan prioritas',
          'Reorder point formula: lead time × daily velocity + safety stock',
          'Stock opname mingguan: SOP sederhana untuk solo founder',
          'Tools: Google Sheets → Mekari Inventory → Majoo — kapan upgrade',
          'Antisipasi stockout di kampanye besar: 11.11, 12.12, Ramadan',
        ],
      },
      {
        n: '23',
        title: 'Fulfillment: Packing Sendiri vs 3PL',
        sub: 'Patokan konkret kapan migrasi',
        tags: ['ops'],
        dur: '5 video · 60 mnt',
        del: 'Fulfillment Decision Sheet + Packing SOP',
        subs: [
          'Volume patokan: <100 order/bln solo → 100–500 hire helper → 500+ 3PL',
          'Pilihan kurir Indonesia: J&T, SiCepat, AnterAja, Ninja — service vs biaya per rute',
          'SOP packing efisien: layout meja, stok kemasan, thermal label printer',
          '3PL Indonesia: Shipper, Crewdible, Aturtoko, Mekari Desty Warehouse',
          'SLA marketplace: 1–2 hari handling time — efek langsung ke score toko',
        ],
      },
      {
        n: '24',
        title: 'Customer Service yang Convert',
        sub: 'Response rate >95%, konversi chat 30%+, retur <5%',
        tags: ['ops'],
        dur: '4 video · 50 mnt',
        del: 'CS Script Bank + Retur Policy Template',
        subs: [
          'Auto-reply yang tidak terdengar robotik — cara nulis yang tetap manusiawi',
          'Chat sales framework: greeting → diagnose → recommend → close → upsell',
          'Komplain handling: 3-step (acknowledge, action, apologize) tanpa kasih refund gratis',
          'Retur policy: kapan ganti barang, kapan refund, kapan boleh tolak',
          'Tools: Mekari Qontak, Socialchat, atau native MP chat — kapan upgrade',
        ],
      },
      {
        n: '25',
        title: 'Cashflow Bulanan: Stok, Iklan, Gaji',
        sub: 'Revenue 50jt tapi saldo 2jt? Ini yang perlu dibenahi',
        tags: ['fundamental', 'ops'],
        dur: '5 video · 60 mnt',
        del: '12-Week Cashflow Forecast Sheet',
        subs: [
          'Komponen cashflow e-commerce: in (settlement MP, COD) vs out (stok, iklan, gaji)',
          'Cash conversion cycle: 30–60 hari adalah normal untuk e-commerce Indonesia',
          'Template cashflow 12 minggu rolling — cara isi dan baca',
          'Kapan butuh modal kerja eksternal: KTA, P2P (Modalku, Investree), invoice financing',
          'Red flags: kapan harus kurangi spend iklan, kapan harus stop nambah stok',
        ],
      },
      {
        n: '26',
        title: 'Tim Pertama: Admin, Packer, atau Content Creator Duluan?',
        sub: 'Hire yang menghasilkan, bukan yang bikin nyaman',
        tags: ['ops'],
        dur: '5 video · 65 mnt',
        del: 'First Hire Toolkit: JD + Gaji Benchmark + Onboarding Plan',
        subs: [
          'Patokan kapan hire: admin (>50 chat/hari), packer (>30 order/hari), CC (setelah hook validated)',
          'JD template per role: Admin CS, Packer/Ops, Content Creator',
          'Gaji benchmark Indonesia 2026 per role: Jabodetabek vs daerah',
          'Hiring channel: Glints, Kalibrr, komunitas seller, referensi internal',
          'Onboarding 14 hari: training SOP → trial period → assessment',
          'Probation & exit: aturan main yang jelas dari hari pertama',
        ],
      },
      {
        n: '27',
        title: 'Dashboard Mingguan: 10 Metrik yang Owner Harus Cek',
        sub: 'Decision based on angka, bukan feeling',
        tags: ['fundamental', 'ops'],
        dur: '4 video · 50 mnt',
        del: 'Weekly Dashboard Template (Google Sheets + Looker Studio)',
        subs: [
          'Metrik wajib per minggu: GMV, Net Sales, AOV, Conversion Rate, ROAS, Retur Rate, Repeat Rate',
          'Cara baca Shopee Seller Center & TikTok Shop Analytics dengan benar',
          'Tools dashboard: Kalodata, Tokpi/Compas, atau build sendiri gratis',
          'Weekly review 30 menit: agenda efisien untuk solo founder atau kecil tim',
          'Action triggers: kalau metrik X turun, eksekusi Y — decision tree konkret',
        ],
      },
      {
        n: '28',
        title: 'Roadmap 50jt → 500jt: Apa yang Harus Berubah',
        sub: 'Lompatan struktural menuju 500jt — bukan sekadar double effort',
        tags: ['fundamental', 'growth'],
        dur: '4 video · 55 mnt',
        del: '100M Readiness Checklist + 90-Day Sprint Plan',
        subs: [
          'Audit kesiapan: profit konsisten 3 bulan? Ops jalan tanpa lo 2 minggu? HPP akurat?',
          'Skill yang perlu di-acquire: transisi dari operator jadi owner',
          'Modal yang dibutuhkan per kategori untuk lompat ke 100jt',
          'Multi-SKU expansion: kapan launch SKU ke-2 dan ke-3 tanpa scattered',
          'Kapan upgrade ke Playmaker Room: revenue 300–500jt konsisten 2 bulan = sinyal siap naik tier',
        ],
      },
    ],
  },
];

export const PM_CLUSTERS = [
  {
    n: '01',
    title: 'Growth Strategy',
    modules: [
      {
        n: '01',
        title: 'Strategi Banjir: Decode Cara Brand China Mendominasi',
        sub: 'Playbook Skintific, Originote, Glad2Glow — adaptasi untuk modal lokal',
        tags: ['framework', 'case-study'],
        dur: '5 video · 90 mnt',
        cs: 'Skintific (RMB 800M), Originote, Glad2Glow vs Azarine, Avoskin (counter-strategy)',
        del: 'Banjir Strategy Adoption Framework',
        subs: [
          'Anatomi Strategi Banjir: 1000+ nano seeding + 1–2 hero SKU + dominasi FYP TikTok',
          'Budget allocation real: 30–40% revenue (China brand) vs 10–15% (lokal) — cara bridge gap',
          'Localized R&D: kenapa Skintific reformulasi produk khusus untuk kulit tropis Indonesia',
          'Local entity strategy: PT Skin Solusindo, PT May Sun Yvan — kenapa pakai entitas lokal',
          'Framework adopsi untuk brand lokal dengan marketing budget terbatas',
        ],
      },
      {
        n: '03',
        title: 'Hero Product Doctrine',
        sub: '1 SKU yang bawa brand lo ke 1M+/bln',
        tags: ['framework', 'strategic'],
        dur: '5 video · 85 mnt',
        cs: 'Somethinc Hyaluron Serum, Erigo Hoodie, Wardah Lightening Series',
        del: 'Hero SKU Matrix + Margin Engineering Calculator',
        subs: [
          'Hero SKU benchmark: minimum unit/bulan yang valid untuk di-scale ke 1M',
          'Margin engineering: 5 lever untuk naik dari HPP 30% ke 40–50%',
          'Sub-hero & companion SKU: bundle yang naikin AOV 30–50% tanpa melemahkan hero',
          'SKU rationalization: cara kill 50% katalog tanpa kehilangan GMV signifikan',
          'Hero lifecycle management: kapan launch v2, kapan retire, kapan pivot',
        ],
      },
      {
        n: '04',
        title: 'Audience Laddering & GMV Max Advanced',
        sub: 'ROI 4–8x konsisten, scaling +50% tanpa boncos',
        tags: ['framework', 'case-study'],
        dur: '6 video · 110 mnt',
        cs: 'TikTok Shop Top 100 spend pattern via Kalodata data',
        del: 'GMV Max Scaling Playbook + ROI Target Calculator',
        subs: [
          'Audience laddering: cold → warm → retargeting — di TikTok Ads Manager level advanced',
          'Multi-creative rotation: cara feed 20–50 video kreatif per kampanye tanpa Ad fatigue',
          'Affiliate posts authorization: akses semua video kreator untuk asset GMV Max',
          'LIVE GMV Max optimization: peak hours, host-product matching, ROI per time slot',
          'Scaling rule disiplin: +20% per 2 hari, kapan break, kapan double-budget',
          'Atribusi 1-day vs 7-day: cara baca incremental GMV — bukan vanity GMV',
        ],
      },
      {
        n: '05',
        title: 'Penetration Pricing vs Premium Pricing',
        sub: 'Pilih lane lo dan konsisten — jangan coba semua',
        tags: ['framework', 'strategic'],
        dur: '5 video · 80 mnt',
        cs: 'Skintific (Rp 60–100rb) vs Avoskin (Rp 100–250rb) vs ESQA (Rp 200–400rb)',
        del: 'Pricing Lane Decision Matrix',
        subs: [
          'Pricing lane breakdown: ultra-budget, mass-market, mass-premium, premium, luxury — economics tiap lane',
          'Decoy pricing & anchor pricing yang proven work untuk e-commerce Indonesia',
          'LTV-based pricing: kalau repeat rate 30%+, harga akuisisi pertama bisa agresif',
          'Subscription & recurring revenue: kategori produk yang proven work di Indonesia',
          'Migration pricing: cara naik harga 10–20% tanpa kehilangan loyal customer',
        ],
      },
      {
        n: '06',
        title: 'Repeat Rate & LTV Engineering',
        sub: 'Kunci survive Local Brand Winter',
        tags: ['framework', 'strategic'],
        dur: '5 video · 75 mnt',
        cs: 'Somethinc loyalty tier, Erigo membership, Sociolla repeat program',
        del: 'LTV & Cohort Sheet + CRM Sequence Template',
        subs: [
          'Hitung LTV real e-commerce: cohort analysis manual untuk seller Indonesia',
          'Retention levers: bundle bulanan, refill kit, subscription, loyalty member tier',
          'CRM via WhatsApp Business API: broadcast segmented, automation, re-engagement',
          'Loyalty program yang proven di Indonesia: poin vs cashback vs early access — mana lebih efektif',
          'Win-back campaign untuk customer yang tidak repeat dalam 60–90 hari',
        ],
      },
    ],
  },
  {
    n: '02',
    title: 'Platform Mastery at Scale',
    modules: [
      {
        n: '07',
        title: 'KOL System at Scale: 100 → 1000+ Affiliator',
        sub: 'Dari seeding acak ke affiliate machine yang scalable',
        tags: ['framework', 'case-study', 'ops-scaling'],
        dur: '7 video · 120 mnt',
        cs: 'Skintific 17K kreator aktif, MS Glow program, Scarlett KOL system',
        del: 'Affiliate Operating System — 7 templates',
        subs: [
          'Tier system affiliator: nano, micro, mid, top — beda perlakuan dan ekspektasi performa',
          'Recruitment engine: open program + DM targeting + MCN agency partnership',
          'Briefing terstruktur: weekly call, content brief per tier, hero angle per produk',
          'Performance dashboard untuk manage 1000+ affiliator (KOL.id, Kalodata, Partnerize)',
          'Incentive structure: komisi tier + bonus performa bulanan + sample seeding ongoing',
          'Toxic affiliator management: spam, klaim ilegal, leakage harga — detection dan takedown',
          'MCN partnership: kapan dan bagaimana kerja sama dengan Multi-Channel Network Indonesia',
        ],
      },
      {
        n: '08',
        title: 'Live Commerce Empire',
        sub: 'Multi-host, studio mandiri, 8–16 jam/hari',
        tags: ['framework', 'ops-scaling'],
        dur: '7 video · 130 mnt',
        cs: 'Power Commerce Asia 24-jam studio, Tanah Abang seller scale 0–100jt dalam 4.5 bulan',
        del: 'Live Studio Blueprint + Multi-Host Compensation Sheet',
        subs: [
          'Studio mandiri vs sewa studio: capex Rp 50–200jt vs sewa Rp 5–20jt/bln — economics real',
          'Layout multi-set profesional: A roll, B roll, talkshow corner, demo station',
          'Multi-host SOP: kontrak, gaji base + komisi GMV per shift, rotasi jadwal',
          'Schedule optimization: peak hours Indonesia (sore–malam) + early bird (pagi) strategy',
          'Content engineering per shift: opening promo → demo → peak closing flash sale',
          'Live operations team structure: live director, switcher, runner, CS standby real-time',
          'AI host & avatar: AnyMind deploy di Indonesia 2025 — kapan relevant untuk brand lo',
        ],
      },
      {
        n: '09',
        title: 'Negosiasi dengan Shopee & TikTok Shop Account Manager',
        sub: 'Voucher subsidy, placement, kampanye whitelisting',
        tags: ['framework', 'strategic'],
        dur: '5 video · 80 mnt',
        cs: 'Erigo, Eleven Basic naik ke Shopee Mall — proses dan timeline',
        del: 'AM Pitch Deck Template + Negotiation Checklist',
        subs: [
          'Syarat naik Shopee Mall & Star+: GMV minimum, kategori produk, dokumen',
          'Cara approach Account Manager: profil deck yang menarik, ask yang jelas dan terukur',
          'Negosiasi konkret: voucher subsidi, free ongkir XTRA, homepage placement budget',
          'CPAS Shopee/Tokopedia: requirement, budget minimum, brand whitelist process',
          'Campaign whitelisting untuk: 9.9, 10.10, Ramadan Sale, Birthday Sale',
          'TikTok Mall & TAP (TikTok Partner) program — equivalent untuk TikTok Shop',
        ],
      },
      {
        n: '10',
        title: 'Multi-Marketplace Stack Tanpa Saling Bunuh',
        sub: 'Shopee + TikTok + Tokopedia + Lazada — ROAS positif di semua channel',
        tags: ['framework', 'ops-scaling'],
        dur: '6 video · 95 mnt',
        cs: 'Wardah/Paragon multi-channel, Erigo, Eiger multi-platform',
        del: 'Multi-MP Operating Sheet — channel matrix',
        subs: [
          'Channel positioning yang tepat: TikTok discovery, Shopee niat-beli, Tokopedia premium, Lazada import',
          'Price differentiation antar channel tanpa rusak brand equity',
          'SKU stratifikasi: hero SKU di semua MP, exclusive SKU per MP untuk diferensiasi',
          'Inventory sync real-time: BigSeller, Mekari Desty, Jubelio — comparison dan setup',
          'Order management & fulfillment routing otomatis antar channel',
          'Performance dashboard cross-channel terintegrasi',
        ],
      },
      {
        n: '11',
        title: 'Data Stack: Dari Spreadsheet ke Dashboard Real-Time',
        sub: '30–50 metrik, refresh harian, semua channel terintegrasi',
        tags: ['framework', 'ops-scaling'],
        dur: '5 video · 85 mnt',
        del: 'Looker Studio Brand Dashboard Template',
        subs: [
          'Data sources integration: Shopee API, TikTok Business API, GMV Max reporting, Google Analytics',
          'Tools stack recommendation: Kalodata, Tokpi/Compas, Looker Studio, Google Sheets',
          'Custom dashboard build: GMV, contribution per channel, ROAS per campaign, per affiliator',
          'Cohort analysis manual untuk retention dan repeat rate tracking',
          'Anomali alert system: Slack/WA notifikasi otomatis saat metrik turun >threshold',
        ],
      },
    ],
  },
  {
    n: '03',
    title: 'Team & Ops Scaling',
    modules: [
      {
        n: '12',
        title: 'Org Chart 5–50 Orang',
        sub: 'Struktur yang match dengan stage revenue lo',
        tags: ['team', 'framework'],
        dur: '6 video · 100 mnt',
        cs: 'Erigo team structure, Somethinc/BeautyHaul 200 brand operator model',
        del: 'Org Chart Roadmap + Role-by-Role JD Bank',
        subs: [
          'Org chart benchmark per revenue tier: 100jt, 500jt, 1M, 5M, 10M/bln',
          '4 fungsi inti yang harus solid: Operations, Marketing, Finance, Product',
          'Critical hires dan urutan: Brand Manager, KOL Manager, Live Director, Ops Manager, Performance Marketer',
          'Sequencing hiring: kapan masing-masing role masuk — jangan prematur',
          'Gaji benchmark 2026 per role di Indonesia: Jabodetabek vs daerah',
          'Equity & profit-sharing untuk key hire yang mau long-term',
        ],
      },
      {
        n: '13',
        title: 'Middle Management: Bangun Manager Pertama Lo',
        sub: 'Dari semua keputusan di founder ke divisi yang autopilot',
        tags: ['team', 'framework'],
        dur: '5 video · 85 mnt',
        del: 'OKR Template per Divisi + 1-on-1 Sheet',
        subs: [
          'Promote internal vs hire external manager: pros, cons, dan kapan masing-masing',
          'Leadership training untuk first-time manager: apa yang perlu di-coach',
          'Delegation framework: RACI matrix untuk e-commerce brand',
          'OKR system per divisi: contoh OKR Marketing, Ops, Finance untuk brand commerce',
          'Weekly 1-on-1 SOP, monthly performance review, quarterly planning — format efisien',
          'Common pitfall: founder yang tidak bisa let go — pattern dan cara keluar dari trap ini',
        ],
      },
      {
        n: '14',
        title: 'Operations at Scale: SOP, SLA, Automation',
        sub: 'Operasional brand jalan 14 hari tanpa founder intervensi',
        tags: ['ops-scaling'],
        dur: '6 video · 100 mnt',
        del: '30 SOP Library Pack — siap copy-paste',
        subs: [
          '30 SOP wajib yang harus ada: listing, packing, CS, returns, ads, live, dll',
          'SLA per fungsi yang clear: response time, packing time, settlement, refund turnaround',
          'Automation tools: chatbot (Mekari Qontak, Wati), auto-allocator order, thermal label printer',
          'Warehouse setup yang scalable: layout, sistem FIFO/FEFO, picking system',
          '3PL partnership level advance: Shipper, Crewdible, AnyMind Fulfillment Indonesia',
          'Crisis ops protocol: stockout mendadak, kurir mogok, gudang banjir — SOP masing-masing',
        ],
      },
      {
        n: '16',
        title: 'Crisis Management',
        sub: 'Fraud, brand attack, KOL skandal, supply disruption',
        tags: ['strategic', 'ops-scaling'],
        dur: '6 video · 95 mnt',
        cs: 'MS Glow vs PS Glow, skandal KOL beauty Indonesia 2023–2025',
        del: 'Crisis Playbook — 5 SOP per jenis krisis',
        subs: [
          'Fraud affiliator: sistem detection (return rate tinggi, klaim ilegal), takedown, blacklist',
          'KOL skandal/cancel culture: damage control PR, statement framework dalam 24 jam',
          'Supply chain disruption: backup supplier protocol, force majeure, komunikasi konsumen',
          'Negative review wave: cara respons di MP, sosmed, dan kalau sampai ke regulator',
          'Founder burnout: signal awal dan recovery plan — topik yang jarang dibahas publik di Indonesia',
          'Legal escalation: IP infringement, sengketa supplier, takedown kompetitor ilegal',
        ],
      },
    ],
  },
  {
    n: '04',
    title: 'Finance & Modal',
    modules: [
      {
        n: '17',
        title: 'Unit Economics yang Dewasa',
        sub: 'Contribution margin per SKU per channel — melampaui gross margin',
        tags: ['finance', 'framework'],
        dur: '5 video · 90 mnt',
        del: 'Unit Economics Master Sheet (P&L per SKU + per channel)',
        subs: [
          '4-layer P&L: Revenue → Net Revenue → Gross Profit → Contribution Margin — cara baca tiap layer',
          'CAC tracking yang akurat: per channel, per campaign type, per affiliator tier',
          'Hidden cost yang sering tidak di-hitung: retur, free ongkir share, voucher loss, MP penalty',
          'Per-SKU P&L template untuk kategori Fashion / Beauty / F&B',
          'Per-channel P&L: ROI Shopee vs TikTok Shop vs D2C — comparison real',
        ],
      },
      {
        n: '18',
        title: 'Cashflow Engineering',
        sub: 'Modal kerja, settlement loop, inventory cycle — 13 minggu ke depan',
        tags: ['finance', 'framework'],
        dur: '6 video · 100 mnt',
        cs: 'Brand fashion lokal yang gagal scaling karena cashflow — studi kasus tanpa nama',
        del: '13-Week Cashflow Engine + Working Capital Optimizer',
        subs: [
          'Cash conversion cycle untuk brand commerce Indonesia: lokal vs produk impor',
          'Settlement timing per MP: Shopee 5–14 hari, TikTok 7–14 hari — cashflow implication',
          'Inventory turnover benchmark: fashion 6–12x/tahun, beauty 4–8x, F&B 8–15x',
          'Modal kerja eksternal: KTA, P2P (Modalku, Investree, Akseleran), invoice financing, PO financing',
          'Supply chain financing untuk produk impor — opsi dan syarat di Indonesia',
          '13-week rolling cashflow forecast: 3 skenario (base, optimistic, worst) — cara buat dan baca',
        ],
      },
      {
        n: '19',
        title: 'Tax Planning & Multi-Entity',
        sub: 'Struktur legal yang optimal pajak + siap audit + scalable',
        tags: ['finance', 'strategic'],
        dur: '5 video · 80 mnt',
        del: 'Tax & Entity Decision Tree',
        subs: [
          'PPh final UMKM 0.5%: batas threshold Rp 4.8M/tahun — kapan harus migrasi ke PPh badan',
          'PPN & PKP: kapan wajib jadi PKP, efek ke harga jual dan margin',
          'Multi-entity setup: PT per brand + PT holding — struktur yang efisien pajak',
          'Personal vs corporate expenses: apa yang bisa di-deduct dan apa yang tidak',
          'Bookkeeping audit-ready: Mekari Jurnal, Accurate, Zahir — comparison dan kapan pakai',
          'Tax planning untuk founder: dividen vs gaji vs kompensasi lain — optimasi legal',
        ],
      },
      {
        n: '20',
        title: 'Fundraising: Bootstrap, Angel, VC, Aggregator',
        sub: 'Kapan ambil modal, dari siapa, dengan terms apa',
        tags: ['finance', 'strategic'],
        dur: '6 video · 110 mnt',
        cs: 'Rose All Day, ESQA, BASE raise; Hypefast acquisition 25+ brand model',
        del: 'Pitch Deck Template + Term Sheet Cheat Sheet',
        subs: [
          'Opsi funding 2026: bootstrap, debt, angel investor, VC, brand aggregator',
          'Aggregator Indonesia/SEA: Hypefast, Una Brands, Rainforest — economics dan deal terms',
          'VC yang aktif di brand commerce: Monk\'s Hill, Jungle, AC Ventures, Init-6 — apa yang mereka cari',
          'Metrics yang investor mau lihat: LTV/CAC ratio, repeat rate, contribution margin, NPS',
          'Term sheet 101: pre/post-money valuation, dilution, liquidation preference, anti-dilution',
          'Reality Local Brand Winter 2024–2026: valuasi turun, due diligence ketat, ekspektasi realistis',
        ],
      },
    ],
  },
  {
    n: '05',
    title: 'Brand, D2C & Multi-Channel',
    modules: [
      {
        n: '22',
        title: 'Brand Building Beyond Marketplace',
        sub: 'Equity yang bertahan saat algoritma berubah',
        tags: ['strategic', 'framework'],
        dur: '6 video · 95 mnt',
        cs: 'Erigo, Wardah, Compass Footwear, Sociolla brand-building approach',
        del: 'Brand Book Template + Content Pillar Planner',
        subs: [
          'Brand identity vs brand experience: 3 layer yang harus dibangun secara bersamaan',
          'Hero story development: kenapa brand ini ada — bukan "passion-driven" narrative klise',
          'Visual identity yang ngeunci: warna, tipografi, mood board yang konsisten cross-channel',
          'Content pillar 70/20/10: produk / edukasi / community — cara implementasi',
          'PR tanpa bayar PR agency: cara dapat coverage di Liputan6, Detik, Kompas, Tirto',
          'Brand partnership & kolaborasi: limited edition, co-marketing dengan brand yang complementary',
        ],
      },
      {
        n: '23',
        title: 'D2C Strategy Indonesia: Kapan Bangun Shopify, Kapan Tidak',
        sub: 'Reality check — D2C Indonesia ≠ D2C USA',
        tags: ['strategic', 'framework'],
        dur: '7 video · 120 mnt',
        cs: 'Erigo D2C, Sociolla, Hijup, Saturday\'s Brand, Cleo Water',
        del: 'D2C Readiness Scorecard + Shopify Setup Checklist',
        subs: [
          'D2C readiness check dengan angka: min. 500jt/bln + awareness 30%+ + repeat rate 30%+',
          'Platform comparison: Shopify vs WordPress/WooCommerce vs Sirclo (lokal) — economics',
          'Traffic strategy D2C Indonesia: Meta Ads, Google Ads, SEO, owned WA Blast',
          'Payment & logistics: Midtrans/Xendit + J&T/JNE COD via 3PL',
          'CRM advantage dari D2C: 1st party data yang tidak bisa lo dapat dari marketplace',
          'Multi-channel sequencing: MP untuk akuisisi baru, D2C untuk repeat customer',
          'Reality check: 5–15% revenue D2C adalah normal brand Indonesia — bukan 50%+',
        ],
      },
      {
        n: '24',
        title: 'Masuk Lifestyle MT: Sociolla, Guardian, Watson, Sephora Indonesia',
        sub: 'Masuk beauty & lifestyle retail — listing fee, buyer pitch, angka real',
        tags: ['strategic', 'framework'],
        dur: '7 video · 115 mnt',
        cs: 'Avoskin di Watson, Whitelab di Sociolla, Somethinc di Guardian, Erha di Sephora Indonesia',
        del: 'MT Pitch Deck Template + Margin Stack Calculator',
        subs: [
          'Landscape Lifestyle MT Indonesia: Sociolla (online + offline), Guardian 800+ outlet, Watson 500+, Sephora Indonesia, AEON — fokus beauty, skincare, wellness, F&B premium',
          'Listing fee, slotting allowance, trading term Sociolla vs Guardian vs Watson — angka real yang jarang dibahas publik',
          'Margin requirement lifestyle MT: brand share ~35–45%, retailer ~20–30% — lebih favorable dari FMCG mass retail',
          'Pitch process step-by-step: buyer meeting, sample review, trial period, full rollout',
          'SKU strategy lifestyle MT vs online: pack size eksklusif, gift set bundle, limited edition untuk retail — diferensiasi tanpa konflik harga online',
          'Distribusi & logistik: warehouse, replenishment cycle, minimum order quantity',
        ],
      },
      {
        n: '25',
        title: 'GT & Distribusi: Wholesale, Distributor, General Trade',
        sub: 'Channel offline yang relevan setelah brand stabil di atas 1M/bln — warung, grosir, distribusi',
        tags: ['strategic', 'framework'],
        dur: '7 video · 120 mnt',
        cs: 'Model distribusi Kapal Api, brand UMKM kuliner yang scale via distributor',
        del: 'Distribution Margin Stack + Distributor Contract Template',
        subs: [
          'Model distribusi Indonesia: Produsen → Distributor Nasional → Sub-Distributor → Grosir → Warung',
          'Deal terms dengan distributor: NET 30/60/90, volume commitment, exclusivity clause',
          'Pricing structure yang benar: HET, HJD, HJG — definisi dan cara kalkulasi stack margin',
          'Channel conflict prevention: aturan main agar distributor tidak jual online dan rusak harga',
          'Sales force strategy: hire sales agent sendiri vs bergabung dengan existing distributor',
          'Prioritas wilayah: Jabodetabek dulu vs ekspansi nasional langsung — tradeoff',
        ],
      },
    ],
  },
  {
    n: '06',
    title: 'Endgame — Multi-Brand, Export, Exit',
    modules: [
      {
        n: '26',
        title: 'Multi-Brand Strategy',
        sub: 'Kapan launch brand kedua, ketiga',
        tags: ['strategic', 'framework', 'case-study'],
        dur: '5 video · 90 mnt',
        cs: 'Paragon (Wardah → 8 brand), BeautyHaul/Somethinc, Avo Innovation/Avoskin',
        del: 'Multi-Brand Decision Tree + Brand Architecture Worksheet',
        subs: [
          'Single brand vs multi-brand: kapan diversifikasi makes sense secara finansial',
          'Shared infrastructure: tim, warehouse, finance — tapi separate brand equity',
          'Brand architecture: Branded House vs House of Brands vs Endorsed — pilih yang mana',
          'SKU cannibalization risk: cara design portfolio yang tidak self-compete',
          'Talent & culture management saat multi-brand mulai jalan bersamaan',
          'Akuisisi brand kompetitor sebagai shortcut ekspansi — mechanics dan valuation',
        ],
      },
      {
        n: '27',
        title: 'Export & ASEAN Expansion',
        sub: 'Malaysia, Filipina, Thailand, Vietnam — lewat TikTok Shop cross-country',
        tags: ['strategic', 'framework'],
        dur: '6 video · 110 mnt',
        cs: 'Somethinc Malaysia, Skintific cross-country expansion, Erigo Singapore',
        del: 'ASEAN Expansion Sheet + Country Regulatory Cheat Sheet',
        subs: [
          'Market readiness: kategori produk yang proven work di masing-masing negara ASEAN',
          'Regulasi per negara: NPRA Malaysia, FDA Filipina, FDA Thailand — timeline registrasi',
          'Entity setup: incorporate entitas lokal vs model distributor partnership',
          'Logistik: cross-border via Shopee International vs bangun local warehouse',
          'Marketing localization: recruit KOL lokal, adaptasi konten, bahasa per negara',
          'Tim strategy: hire lokal vs manage remote dari Indonesia — pertimbangan dan cost',
        ],
      },
      {
        n: '28',
        title: 'Exit Strategy: Akuisisi, Strategic Sale, IPO',
        sub: 'Valuasi, due diligence, earn-out — framework untuk founder yang mau keluar',
        tags: ['strategic', 'framework', 'case-study'],
        dur: '6 video · 110 mnt',
        cs: 'Hypefast 25+ acquisitions, Rose All Day, ESQA, Avoskin founder perspective',
        del: 'Exit Readiness Scorecard + Valuation Calculator',
        subs: [
          'Brand aggregator landscape Indonesia/SEA: Hypefast, Una Brands, Rainforest — economics dan terms',
          'Strategic acquirer: Paragon, Mustika Ratu, Unilever, L\'Oréal Indonesia — process approach',
          'Valuasi consumer brand: revenue multiple 1–3x vs EBITDA multiple 5–12x — faktor penentu',
          'Due diligence preparation: financials, legal, ops, customer data — apa yang harus clean',
          'Earn-out structure post-acquisition: founder stay 2–3 tahun — ekspektasi dan proteksi',
          'Reality of post-exit: founder yang regret vs yang grateful — honest conversation',
        ],
      },
    ],
  },
];

export const WR_CLUSTERS = [
  {
    n: '01',
    title: 'Influence & KOL Ecosystem',
    modules: [
      {
        n: '01',
        title: 'KOL 360°: 5 Tier, 1 Mesin Konversi',
        sub: 'Dari nano sampai Sultan Andara — stack yang benar, bukan asal endorse',
        tags: ['kol-360', 'tactical'],
        dur: '10 video · 210 mnt',
        cs: 'Glad2Glow Rp102M affiliate/bln, Skintific Rp61M (Kalodata Q3 2025). Raffi Ahmad: Rp40–250jt per deliverable. Tasya Farasya 1 video skincare > Raffi 3 video untuk commercial intent.',
        del: 'KOL 360° Budget Allocator + KOL Contract Template 2026 (ad auth clause, PPh 21) + Spark Ads Authorization Checklist + Rate Negotiation Script',
        subs: [
          'Anatomi 5 tier Indonesia 2026: nano (10k-50k), mikro (50k-100k), mid (100k-500k), mega (500k-1M), artis (1M+) — rate, ROAS, use case per tier',
          'Rate benchmark real: nano Rp0-150k/video, mid Rp1-10jt, mega Rp15-50jt, artis Rp40-250jt+ per deliverable — negotiated rate 25-40% di bawah published',
          'KOL Artis vs KOL Beauty/Lifestyle: fanbase loyalty vs commercial intent. Artis tier-A = high reach, low conversion intent untuk produk serious/skincare',
          'Brief framework per tier: nano (loose, beri sample), mikro (semi-brief + script angle), mid (full brief), mega/artis (full creative control terbatas + legal review)',
          'Authorization hack: konten KOL → GMV Max + Spark Ads. Wajib pasang clause 60-day ad usage sebelum bayar. Royalty kalau extend.',
          'Stacking formula: 50 nano + 10 mikro + 3 mid + 1 mega per launch window vs single Rp150jt artis — ROI comparison actual',
          'Negotiation: multi-deliverable paket, exclusivity category, rev share kapan work (rare, artis biasanya refuse), "broken paket" tactic',
          'Anti-mega-only trap: cap mega/celebrity maks 25% budget bulanan. Brand yang 80% di 1 artis = content kering 30 hari post-endorse',
          'Hidden cost: PPh 21 KOL, BPOM compliance skincare/F&B, retake fee, mid-production brief revision, agency markup 20-30%',
          'Case study wall: Skintific Symwhite + Tasya Farasya, Whitelab Centella, Glad2Glow Vitamin Series, Originote Toner Pad, MS Glow era 2022',
        ],
      },
      {
        n: '03',
        title: 'Affiliate Army at Scale: 1000+ Kreator, 1 Funnel',
        sub: 'Dari 18% activation ke 40%+ — Bronze/Silver/Gold tier system',
        tags: ['affiliate', 'tactical'],
        dur: '11 video · 210 mnt',
        cs: 'Skintific ~17k kreator (32% revenue dari affiliate). Glad2Glow >50% revenue affiliate (Kalodata Q3 2025). Originote payback sample ~21 hari.',
        del: 'Affiliate Tier System Sheet + Sample Seeding Tracker (40% activation) + WA Onboarding Sequence Template + Fraud Detection Sheet + PPh 21 Bukti Potong Template',
        subs: [
          'Anatomy Skintific 17k kreator: distribusi nano/mid/mega, 200 top performer = 60% GMV affiliate — proof arsitektur tier works',
          'Bronze/Silver/Gold tier: komisi 8% → 12% (hit 5jt GMV/30hari) → 18% + quarterly rebate (hit 25jt GMV/30hari)',
          '30-Day Commission Lock Rule TikTok: naik komisi langsung, turun komisi butuh 30-day grace period',
          'Sample seeding economics: COGS maks 25% retail, ongkir included, target hit rate 40%+, payback period ≤45 hari',
          'Activation playbook: 7-day onboarding sequence — welcome WA → sample dispatch → reminder 48jam pasca-terima → live brief mingguan (18% → 40%+)',
          'Anti-poaching: eksklusivitas kategori 90 hari, monthly cash bonus Gold tier, early-access SKU baru, paid content collab',
          'Anti-gaming: alamat sama, IP sama, ATC tanpa checkout >90%, refund rate >15%. Detection spreadsheet + Seller Center analytics.',
          'Komisi dinamis TikTok Shop 2026: platform 1-10% + dinamis 4-8% + cap Rp650k/item (efektif 18 Mei 2026) — impact ke affiliate net payout',
          'Spark Ads Floor Rule: Shop Ads commission minimal 1/3 standard affiliate rate (TikTok Seller University official)',
          'Recruitment: outbound DM via Kalodata top performer kompetitor, referral bonus 5% commission seumur hidup untuk yang berhasil ajak kreator baru',
          'PPh 21 compliance: bukti potong, threshold Rp4.5jt/bln, cara handle kreator self-employed vs PT/CV',
        ],
      },
      {
        n: '04',
        title: 'Internal Affiliate System: Pabrik Kreator In-House',
        sub: 'Build your own army — kontrol penuh, brand voice konsisten',
        tags: ['affiliate', 'internal-team'],
        dur: '10 video · 190 mnt',
        cs: 'Brand fashion Jakarta 35 internal creator, kontribusi 40%+ konten organic feeding GMV Max (anonim 2024-2026). Break-even per video internal Rp50-80rb vs external Rp150-250rb.',
        del: 'Internal Creator P&L Calculator + Recruitment Funnel Sheet + 14-Day Bootcamp Curriculum + 100 Brief Angle Library (Excel+Notion) + Studio Mini Spec Sheet 5 workstation <Rp15jt + JD & Contract Template',
        subs: [
          'Internal vs external: kontrol & brand voice konsisten vs viral lottery external. Strategic trade-off + break-even per video comparison.',
          'Recruitment channels 2026: Glints, Kalibrr, Jobstreet, kampus komunikasi/broadcast (UPH, Binus, IKJ), komunitas TikTok kreator lokal',
          'Compensation: base part-time Rp3-5jt/bln + komisi 3-5% attributed GMV + bonus Rp500k-2jt per video viral (>100k views) + probation 60 hari',
          'JD framework: "1 creator = 1 angle/persona" — cewek kantor, ibu muda, gym goer, skincare enthusiast. Avoid creator generic.',
          'Studio mini setup per workstation: ring light Rp300rb + lavalier mic Rp200rb + backdrop + tripod = <Rp3jt. 5 workstation = <Rp15jt total.',
          'Output math: 1 creator × 4 video/hari × 5 hari = 80 video/bln. 10 creator = 800 video/bln ongoing.',
          'Brief library reusable: 50 hook angle + 20 education + 15 demo + 10 unboxing + 5 transformation. Assign per persona.',
          'Onboarding 14-day bootcamp: week 1 brand DNA + product knowledge + tools. Week 2: output 10 video + detailed feedback per video.',
          'Internal creator account: akun pribadi (lebih organik algoritma) vs brand persona akun (predictable) — hybrid strategy',
          'Break-even per video: internal Rp50-80rb. External (sample+komisi+bonus) Rp150-250rb. Break-even = Rp800rb GMV per video attributed.',
        ],
      },
    ],
  },
  {
    n: '02',
    title: 'Traffic Hacking & Viral Launch',
    modules: [
      {
        n: '05',
        title: 'Clipper System: Content Multiplication Engine',
        sub: '1 konten jadi 150 distribusi — Hormozi playbook untuk e-commerce Indonesia',
        tags: ['clipper', 'content-multiplication'],
        dur: '10 video · 175 mnt',
        cs: 'Alex Hormozi 100M+ views/bln dari clipper army. Cluely 700+ clipper. Brand beauty ID ~50 external clipper (anonim 2024-2026). NPR Mei 2026: 40.000+ freelance clipper dalam 1 network.',
        del: 'Clipper Economics Calculator + 1 Live to 30 Clips SOP Template + External Clipper Brief + UTM Attribution Sheet + AI Clipping Tool Comparison 2026',
        subs: [
          '2 tipe clipper: external (clip dari live brand, repost akun pribadi + tag affiliate link) vs internal (editor slice untuk multi-repost akun brand)',
          'Internal clipper SOP: 1 live 60 mnt → 5 hook clips (15-30s) + 10 education (45-90s) + 5 viral moments + 5 social proof + 5 demo = 30 clips',
          'External clipper recruitment: open call via TikTok/IG + landing page. Payment: CPM Rp200-500/1.000 views, CPS 8-18%, atau hybrid base Rp500k-2jt/bln.',
          'Content multiplication math: 1 live × 30 clips × 50 clipper × 3 repost cycle = 4.500 distribusi. Cost Rp8-18jt vs equivalent paid ads reach.',
          'AI clipping tools 2026: Opus Clip, Vizard, Klap (AI auto-detect highlight moment) — hemat 70% edit time. CapCut, Descript untuk manual.',
          'Brief minimum external: produk fokus + talking points BPOM-compliant + affiliate link format + deadline 48 jam + larangan watermark platform lain',
          'Anti-cannibalization: max 2x upload sama dalam 7 hari, min 6 jam jeda antar repost, caption + hook harus beda per upload',
          'Attribution: UTM per clipper grup + affiliate link unique per clipper + Kalodata cross-validation untuk track top performing clip',
          'Daftarkan external clipper sebagai affiliate juga: combo CPM + komisi affiliate. Retention naik 50%+ dengan model ini.',
          'Watermark akun brand pada semua clip — tipis pojok kanan bawah. Cegah pencurian konten + brand exposure setiap share.',
        ],
      },
      {
        n: '06',
        title: 'Buzzer & Engagement Pod: Grey Zone, Blak-Blakan',
        sub: 'Risk assessment jujur + white-hat alternative yang sama efektif',
        tags: ['grey-area', 'traffic-hacking'],
        dur: '8 video · 130 mnt',
        cs: '⚠️ Anonim. Brand A skincare 2024: shadowban 2 minggu, recovery 4 bulan. Brand C F&B: coordinated WA blast + affiliator wave → 1M views organic 3 jam (0 fake).',
        del: 'White-Hat Initial Burst Playbook (5-channel) + Risk Assessment Decision Sheet + Reverse Seeding Protocol + Algoritma Flag Detection Sheet',
        subs: [
          '⚠️ Grey-area disclosure: modul ini dibahas blunt, bukan endorse. Tujuan: informed decision. Hegemoni recommend white-hat path.',
          'Buzzer industry Indonesia rate publik 2026: view TikTok Rp50-200/1.000 view, komentar real Rp200-1.000/komentar, follower Rp100-500/follower (Buzzertop, Indobuzzer, JasaBuzzer.com, RajaKomen)',
          'Engagement pod TikTok: grup Telegram/WA/Discord seller saling boost. Quid pro quo. Skala 500-5.000 anggota per pod.',
          'Initial engagement window: 30-60 menit pertama penentu FYP push. Test batch 200-500 user menentukan distribusi wider audience.',
          'Signal yang TikTok flag: like spike tanpa watch time, komentar generic akun baru, follower tanpa engagement. Shadowban 7-14 hari (distribusi drop 80%+).',
          'Risk real 2026: TikTok enforcement naik 340% YoY. 51.000+ video AI/synthetic dihapus 2H 2025. 8.600 akun banned (NPR data).',
          'Comparison matrix: buzzer paid Rp50-500rb per burst vs pod (effort+reciprocity) vs reverse seeding Rp1.5-4jt (100% white-hat, full organic).',
          'White-hat alternative — sama efektif: Broadcast WA ke buyer last 30 hari + top 100 list + push affiliator wave 1 (30 nano) dalam 30 mnt pertama. Cross-post IG Reels.',
          'Decision tree: flagship account = never. Secondary/testing = low budget dengan spread 5-10 video, max 1.500 view per video. Launch strategic = white-hat full.',
          'Komentar real dari akun karyawan/family = zero risk. Akun secondary brand sebagai "customer review" = borderline grey, disclosure wajib.',
        ],
      },
      {
        n: '07',
        title: 'Campaign Viral: Launch SKU Trending dari Day 1',
        sub: 'Pre-launch 30 hari → Day 1 blow-out → 7-day post-optimization',
        tags: ['viral', 'launch', 'tactical'],
        dur: '10 video · 180 mnt',
        cs: 'Skintific Symwhite, Whitelab Centella, Glad2Glow Vitamin Series, Originote Toner Pad, Scarlett variant — semua pakai pre-seeding + Day 1 coordinated blow-out.',
        del: '30-Day Launch Calendar Template + Pre-Order Wishlist Tracker + Affiliator Wave 1 Coordinator Sheet + Pre-Launch Content Brief Library + Launch Budget Allocator',
        subs: [
          'Anatomy viral launch 30-day: pre (D-30 to D-1), launch day blow-out, post-launch optimization (D+1 to D+30)',
          'Pre-seeding D-30 to D-14: 50-100 nano kreator dapat sample sebelum public listing. NDA optional. Request konten teaser D-7.',
          'Mid-tier KOL pre-launch D-14 to D-7: 3-5 mid untuk unboxing teaser dengan kode pre-order eksklusif first-100',
          'Wishlist build-up: target 5.000+ wishlist sebelum launch = 3x estimated Day 1 order. TikTok Shop + Shopee "notify when available" feature.',
          'Day 1 launch: flash sale 24 jam + live commerce blow-out 8+ jam + push affiliator wave 1 (top 30 nano + 10 mid) + Spark Ads pre-launch top content',
          'GMV Max coordinated: LIVE GMV Max launch H-3 (TikTok recommendation, minimum 3 hari learning). Product GMV Max aktif Day 1.',
          '7-day post-launch gate D+3: kalau hit <60% target, diagnose cause (konten? affiliate push? ad budget?) dan pivot sebelum D+7.',
          'PR media tier-2 untuk "rumor launch" artikel: IDN Times / Female Daily / Beauty Journal Rp5-15jt — build buzz sebelum listing public.',
          'Discount tier launch: 50% off first 500 order, 30% off berikutnya, 20% normal. Urgency built-in tanpa bakar semua margin.',
          'Failed launch pattern: langsung flash sale tanpa pre-seeding, 1 mega tanpa nano backup, komisi affiliate kecil di launch — no push.',
        ],
      },
      {
        n: '08',
        title: 'Kill Product Protocol: Matiin SKU Tanpa Rusak Brand',
        sub: 'Decision matrix + 90-day phase-out — keberanian kill setajam keberanian launch',
        tags: ['tactical', 'lifecycle'],
        dur: '9 video · 120 mnt',
        cs: 'Skintific retire variant moisturizer lama coordinated dengan new launch. Anonim: brand kosmetik "farewell limited edition" — sold out clearance + engagement naik.',
        del: 'Kill-or-Keep Decision Matrix Sheet + 90-Day Phase-Out Timeline + Affiliator & Customer Comms Templates + Bridge Product Mapping Sheet',
        subs: [
          'Decision matrix kill atau keep: GMV margin contribution last 90 hari, repeat rate, return rate, content velocity (affiliator masih push?), inventory momentum',
          'The 3-Strike Rule: 3 launch boost/promo cycle tanpa hit target = kill. Hindari "satu kali lagi" mindset yang makan listing energy.',
          'Clearance yang tidak rusak brand: bundle dengan hero SKU (BOGO-style), gift-with-purchase, donasi/CSR untuk stigma overstok — daripada discount agresif',
          'Listing management: archive (data preserved, tidak muncul search) vs delete vs hide. Jangan delete kalau ada review + SEO equity.',
          'Komunikasi affiliator tier Gold/Silver: broadcast WA "SKU X discontinue D+30, bridge ke SKU Y" + sample swap dengan SKU baru.',
          'Customer messaging repeat buyer: WA/email "terima kasih loyal ke SKU X, berikut opsi Y dengan voucher 15%". Jangan ghost loyal customer.',
          'Phase-out timeline: D-60 comms affiliator, D-45 stop ad spend, D-30 flash sale wave 1, D-15 bundle, D-0 archive listing.',
          'Stop ad spend dulu sebelum announce: observe organic baseline 14 hari. Kalau <30% normal, confirm kill.',
          'Anti-pattern fatal: langsung remove listing tanpa announce — customer komplain rame di komentar — rating brand turun 0.3 bintang.',
          'Konten "kenapa kami discontinue SKU X": transparansi = trust naik. "Kami dengar feedback..." = brand yang dengerin customer.',
        ],
      },
    ],
  },
  {
    n: '03',
    title: 'Ads Mastery — GMV Max, Shopee & CPAS',
    modules: [
      {
        n: '09',
        title: 'GMV Max Decoded: Hidden Settings & Anti-Boncos Protocol',
        sub: 'Mandatory per Juli 2025 — satu-satunya format TikTok Ads. Kuasai atau bakar duit.',
        tags: ['ads', 'gmv-max', 'anti-boncos'],
        dur: '12 video · 240 mnt',
        cs: 'Garoblogz Q3 2025: rata-rata seller "lempar 7 hasil 3-5". Sakura Baru LIVE GMV Max: +53.8% GMV uplift, 9.6× ROI (TikTok official case). Brand kosmetik boncos Rp80jt/bln dari default ROI.',
        del: 'Target ROI Anti-Boncos Calculator + 4-Hour Rule Monitoring Sheet + Bulk Creative Exclusion Audit + ROI Protection Eligibility Checklist + Multi-Account Split Diagram + External Ledger Pembukuan Template',
        subs: [
          'GMV Max mandatory 15 Juli 2025: satu-satunya format TikTok Shop Sales objective. Video Shopping Ads + Product Shopping Ads sunset.',
          'Math anti-boncos: ROI minimum = 1 ÷ (Margin Kotor - % komisi platform - % komisi dinamis - % affiliate - % fulfillment - % return). Margin 40%, fee 12%, return 8% → ROI floor ~3.6',
          'Default Target ROI suggestion TikTok 1.9-2.5 = boncos zone untuk brand margin <40%. Jangan blindly accept — hitung dulu.',
          'ROI Protection (eff. 25 Feb 2026): eligible jika daily ROI <90% target DAN ≥20 daily orders. Tidak eligible: edit produk mid-day, pause campaign, manual ROI change >2x LIVE/>1x Product, Max delivery mode, akun suspended.',
          'Primary ad account discipline: pindah primary = auto-pause SEMUA GMV Max active. Dedicated primary, jangan ganti sembarangan.',
          'Multi-account split: pisah Product GMV Max dan LIVE GMV Max untuk isolation attribution + diagnose per campaign type.',
          'LIVE GMV Max: launch H-3 sebelum live actual (TikTok recommendation). Minimum 3 hari run. Target ROI +20% di atas Product baseline.',
          'Affiliate authorization: Broad (semua konten authorized) vs Case-by-Case. Spark Ads commission: minimum 1/3 standard affiliate rate.',
          'Boncos Protocol 4-Hour Rule: spend >40% daily budget, order <3 dalam 4 jam — action: lower ROI -10% + bulk exclude creative <2% CTR.',
          'Bulk creative exclusion: Seller Center → Shop Ads → Creative Hub. Filter <2% CTR, mass exclude. Lakukan setiap Jumat.',
          'Misleading attribution: GMV Max attribute SEMUA sales (organic + affiliate + paid). Gunakan Spillover Reporting + external ledger untuk cross-check.',
          'Jangan touch LIVE GMV Max settings dalam 3 hari pertama. Jangan pause mid-day. Jadwalkan ROI change di Senin pagi.',
        ],
      },
      {
        n: '10',
        title: 'Shopee Ads Stacking: Search × Discovery × Live × Ad Groups',
        sub: '4-layer stack + budget allocation rasional — yang brand top-10 lakuin',
        tags: ['ads', 'shopee', 'tactical'],
        dur: '10 video · 180 mnt',
        cs: 'Brand top-10 TikTok Shop (Skintific, Glad2Glow, Xiaomi, Scarlett) semua dominate Shopee parallel via 4-layer ads stack. Discovery Ads PDP targeting kompetitor: ROAS 8-15x.',
        del: 'Shopee Ads 4-Layer Budget Sheet + Keyword Research Master Sheet + Negative Keyword Library per Kategori + Discovery Ads PDP Targeting Playbook + Live Ads Timing Calendar + Ad Groups Migration Template',
        subs: [
          '4-Layer Shopee Ads 2026: Search (high-intent) + Discovery (browsing) + Shop Ads (brand) + Live Ads (retargeting/acquisition) + Ad Groups (baru 2025)',
          'Budget allocation 50/30/20 rule: Search 50% (high-intent floor), Discovery 30% (top-funnel), Shop Ads 20% (brand). Live Ads slot terpisah situational.',
          'Ad Groups (Shopee 2025): group by sales performance (best/avg/low), by promotion, by category. Min 2 produk per group. Replace 50 single-product campaign.',
          'Keyword advance: long-tail "[produk] untuk kulit sensitif berjerawat" vs broad. Negative keyword wajib (DIY, review, vs, competitor names).',
          'Bid management: start manual 60-70% suggested bid, monitor 3 hari, naik 10% per 3 hari kalau impression <1k. Switch automatic setelah 14 hari data.',
          'Discovery Ads hack: product targeting di PDP kompetitor + harga 5% lebih murah + voucher. ROAS 8-15x observable.',
          'Live Ads timing: H-1 hari (pre-live retargeting + acquisition), 30 mnt pre-live (push notif), live duration (boost viewer), post-live 7 hari (visitor retarget).',
          'Recommended Bid deception: Shopee inflate 30-50% dari yang actually win. Start 60-70% suggestion, naikkan per 3 hari.',
          'Voucher Spesial Toko (Shopee 2025): subsidized voucher otomatis dari platform untuk selected seller via AM relationship.',
          'Auto Top-Up Escrow Ads Growth Plan (eff. 2 Feb 2026): 2% sales auto-convert jadi ads credit. Bonus 5% free credits untuk eligible seller.',
        ],
      },
      {
        n: '11',
        title: 'CPAS Hacks: Collaborative Ads yang ROAS 10x',
        sub: 'Meta × Shopee × Tokopedia — bridge yang brand 1M+ pakai diam-diam',
        tags: ['ads', 'cpas', 'attribution'],
        dur: '9 video · 165 mnt',
        cs: 'Brand fashion lokal: scale CPAS Shopee Rp50jt → Rp500jt spend/bln dalam 3 bulan, ROAS sustained 8-10x. Cart abandoner 7-day ROAS 12x consistent.',
        del: 'CPAS Whitelist Email Template Shopee + Brand Profile Deck untuk Whitelist + Catalog Hygiene Audit Checklist + Audience Strategy Tier Sheet + Creative Rotation Calendar 3-Week + CPAS Attribution Reconciliation Sheet',
        subs: [
          'CPAS mechanic: Meta ads → click → marketplace listing → checkout → attribute back to Meta. 70%+ transaksi online Indonesia di marketplace — ini kenapa CPAS powerful.',
          'CPAS Tokopedia: terbuka untuk semua seller. Brand Portal → Marketing Solutions → CPAS Onboarding. UTM parameter CPAS-XXXX wajib per listing.',
          'CPAS Shopee whitelist 2026: whitelist-only. Email marketing.solutions.id@shopee.com subject "CPAS Shopee Request-[Nama Brand]". Approval ≤14 hari kerja.',
          'Catalog hygiene wajib: pricing konsisten dengan MP, image tanpa text overlay >20%, judul match listing, stock real-time sync. Reject reason paling umum: pricing mismatch.',
          'Audience strategy tier: cart abandoners 7-day ROAS 8-15x → product viewers 14-day 5-8x → lookalike 1% 3-5x → interest stacking 2-4x. Mulai dari warm.',
          'Bid & budget: minimum Rp200-500k/hari per ad set untuk Meta ML learning phase. Di bawah itu, algoritma tidak optimize.',
          'Creative rotation 3-week cycle: week 1 — 6 creative per ad set. Week 2 — keep top 2, kill 4, add 4 baru. Week 3 — scale top 2 budget 2x. Repeat.',
          'Atribusi isolation: Meta vs settlement marketplace selalu ada gap 15-25%. Triangulate: GA + UTM strict + organic baseline before/during/after kampanye.',
          'Naikkan budget max 30% per ad set per minggu. Lebih — Meta learning phase reset — ROAS drop 14 hari.',
          'CPAS Tokopedia lebih lenient untuk brand baru kalau Shopee whitelist pending. Mulai dari Tokopedia, parallelize Shopee whitelist request.',
        ],
      },
    ],
  },
  {
    n: '04',
    title: 'Live Commerce & AM Negotiation',
    modules: [
      {
        n: '12',
        title: 'Live Commerce Engineering: Anatomy 60 Menit yang Convert',
        sub: 'Menit-per-menit cue sheet, KPI per host, LIVE GMV Max integration',
        tags: ['live', 'tactical'],
        dur: '12 video · 220 mnt',
        cs: 'Tanah Abang fashion seller: 16 jam/hari, multi-host 8-person rotation. Xiaomi Indonesia: Rp63M Livestream income/bln (Kalodata). Brand kosmetik viral: 24-hour non-stop launch.',
        del: 'Live 60-Mnt Cue Sheet Template + Host KPI Tracker + Multi-Host Rotation Calendar (8-hour) + Studio Setup Spec Sheet Tier 1&2 + Backstage Roles SOP + Post-Live Retargeting Playbook (2-hour window) + AI Host Decision Tree',
        subs: [
          'Anatomy live 60-menit: 0-5 hook+tease promo, 5-15 demo product 1 + flash sale 10mnt, 15-25 Q&A + voucher giveaway, 25-40 product 2+3 bundle, 40-50 testimony + social proof, 50-60 final flash + countdown CTA hard',
          'KPI per host benchmark: retention 5-min >70%, CTR keranjang, ATC rate >15%, conversion >5%, hourly GMV target. Scoring sheet per shift.',
          'Multi-host rotation: tag-team 60-90 menit per host. Host A engagement, Host B closing. 8-16 jam live total = 4-8 host dengan rotasi shift.',
          'Pre-heat 24 jam wajib: broadcast WA notif ke customer list, 3 teaser videos last 24h, LIVE GMV Max aktif H-3, pin jadwal di profil TikTok.',
          'Studio Tier 2 (<Rp15jt): ring light, smartphone Pro, lavalier mic, backdrop, monitor untuk monitor komentar.',
          'Studio Tier 1 (Rp30-100jt): 3-cam multi-angle, mixer audio, prompter, ATEM Mini switcher, dedicated control room.',
          'Backstage team struktur: producer (master schedule+cue), switcher (multi-cam), runner (stock replacement), CS standby (DM real-time), analyst (KPI monitoring).',
          'LIVE GMV Max: aktif H-3 sebelum live, minimum 3 hari run, target ROI +20% di atas Product GMV Max baseline.',
          'Post-live window 2 jam: identify top 10% klip (watch time + ATC spike peak) → Spark Ads boost dalam 2 jam. Visitor live 7-day → retargeting audience.',
          'AI host 2025-2026 (Synthesia, HeyGen): worth untuk F&B basic, electronics spec, fashion size guide. Belum credible untuk hero session premium.',
          'Voucher tier rahasia per 15 menit: "tunggu 15 mnt lagi ada voucher 100rb" — retention boost dramatic. Komentar warm-up 5 menit: staf akun secondary.',
          'Pre-launch live H-1: 30 menit preview produk launch besok + wishlist build. CS standby DM live real-time untuk convert viewer yang ragu.',
        ],
      },
      {
        n: '13',
        title: 'AM Playbook Insider: Negosiasi dengan Shopee & TikTok AM',
        sub: 'Voucher subsidy Rp200M+, beta feature, crisis mediation — yang operator senior lakuin diam-diam',
        tags: ['negotiation', 'am-relationship', 'insider'],
        dur: '10 video · 150 mnt',
        cs: 'Anonim: brand kosmetik dapat voucher subsidy Rp200jt per 11.11 campaign (Strategic AM Shopee). Brand fashion: beta Ad Groups 2024 via AM senior first-access.',
        del: 'Brand Profile Deck Template untuk AM (1-page + 5-page) + AM Power Matrix Cheat Sheet + AM Cadence Calendar + AM History Documentation Sheet (Notion) + Crisis Mediation Email Template + Voucher Subsidy Request Script + Indonesia Gift Etiquette Guide',
        subs: [
          'AM hierarchy: Junior (50-100 brand, power terbatas) → Senior (20-40 brand, voucher 3-5% GMV slot) → Strategic AM (5-15 brand top, voucher 5-10% GMV, homepage placement, beta features, crisis escalation).',
          'Brand profile deck: 1-pager GMV 90 hari + growth trend + top SKU + content velocity + affiliate count + planned ad spend next quarter. AM butuh ini untuk advocate ke supervisor.',
          'Power matrix AM: voucher subsidy 5-10% GMV, category page placement, campaign whitelist (mega sale, 9.9, 10.10, 11.11), beta feature access, dispute escalation.',
          'Reciprocity playbook: AM punya KPI quarterly. Volume growth commitment + eksklusivitas + case study material = AM advocate balik. Win-win.',
          'Cadence: monthly performance review 15-mnt + quarterly strategy lunch/dinner + anniversary gift + big sale pre-call + post-sale debrief.',
          'Request Strategic AM upgrade: GMV consistent ≥Rp1M/bln selama 3 bulan = soft threshold eligible. Request formal ke AM Senior.',
          'AM turnover handling ~6-12 bulan: dokumentasi histori di Notion/Coda (nama, periode, voucher granted, beta accessed, dispute solved). Onboard AM baru dalam 7 hari.',
          'Anniversary gift culture Indonesia: produk brand sendiri Rp200-500rb (most appropriate + brand promo). Hampers Lebaran/Natal OK. Avoid cash (compliance issue).',
          'Crisis mediation via AM: escalation chain ticket → AM WA+email → supervisor 72 jam → Country Lead. Simpan screenshot semua promise.',
          'AM blacklist brand sering drama. Reputasi "collaborative brand" = lebih banyak akses. Always have backup contact: AM + Senior + Supervisor.',
        ],
      },
    ],
  },
];

// Cross-referenced K2 modules that also matter for K3 (War Room)
export const WR_CROSSOVER = [
  { n: '01', from: 'Playmaker Room · Cluster 1 · Growth Strategy', title: 'Strategi Banjir: Decode Cara Brand China Mendominasi', sub: 'Context layer untuk KOL 360° + Affiliate Army — foundational sebelum taktik War Room', tag: 'framework / case-study', dur: '5 video · 90 mnt' },
  { n: '03', from: 'Playmaker Room · Cluster 1 · Growth Strategy', title: 'Audience Laddering & GMV Max Advanced', sub: 'Strategic framework sebelum GMV Max Decoded in-depth di War Room', tag: 'framework / case-study', dur: '6 video · 110 mnt' },
  { n: '06', from: 'Playmaker Room · Cluster 2 · Platform Mastery', title: 'KOL System at Scale: 100 → 1000+ Affiliator', sub: 'Strategic layer untuk KOL 360° + Affiliate Army — War Room masuk ke tactical-level', tag: 'framework / ops-scaling', dur: '7 video · 120 mnt' },
  { n: '07', from: 'Playmaker Room · Cluster 2 · Platform Mastery', title: 'Live Commerce Empire', sub: 'Framework strategic sebelum Live Engineering menit-per-menit di War Room', tag: 'framework / ops-scaling', dur: '7 video · 130 mnt' },
  { n: '08', from: 'Playmaker Room · Cluster 2 · Platform Mastery', title: 'Negosiasi dengan Account Manager Shopee & TikTok', sub: 'Framework negosiasi strategic — War Room masuk ke insider script + tactical detail', tag: 'framework / negotiation', dur: '5 video · 80 mnt' },
  { n: '09', from: 'Playmaker Room · Cluster 2 · Platform Mastery', title: 'Multi-Marketplace Stack Tanpa Saling Bunuh', sub: 'Context multi-channel — War Room fokus tactical TikTok + Shopee saja', tag: 'framework / ops-scaling', dur: '6 video · 95 mnt' },
];

export const TIER_META = {
  brandlab: {
    id: 'brandlab',
    num: 'Tier 01',
    name: 'Brand Lab',
    aud: 'Pemula · 0–500jt/bln',
    desc: 'Foundational program untuk owner brand early-stage. Sequential lock — team-led — technical step-by-step. Covers Shopee Ads, GMV Max, TikTok Ads Manager, CPAS intro, Live, Affiliate.',
    tagline: '"Playbook Dari Operator Yang Masih Jalan. Mulai Dari Dasar."',
    format: 'LMS Sequential · Self-Paced',
    price: 'Rp 500 RB',
    accent: 'amber',
    moduleCount: 28,
    structureLabel: '4 Fase',
    groupNoun: 'Fase',
  },
  playmaker: {
    id: 'playmaker',
    num: 'Tier 02',
    name: 'Playmaker Room',
    aud: 'Mid · 500jt – 10M/bln',
    desc: 'Thematic free-pick · founder-led · framework + case study angka real. Untuk owner brand mid-tier yang mau scale via deep case study Skintific, Glad2Glow, Originote, Wardah, Erigo, Hypefast, dll.',
    tagline: '"Playbook Dari Operator Yang Masih Jalan. Setiap Bulan."',
    format: 'LMS Advance + Monthly Live Cohort',
    price: 'Rp 2.5 JT',
    accent: 'gold',
    badge: 'Populer',
    moduleCount: 25,
    structureLabel: '6 Cluster',
    groupNoun: 'Cluster',
  },
  warroom: {
    id: 'warroom',
    num: 'Tier 03',
    name: 'The War Room',
    aud: 'E-Commerce Specialist',
    desc: 'Premium tactical add-on — TikTok Shop × Shopee EKSKLUSIF. Commercial & Marketing ONLY. Founder-led + operator guest. Tactics, hacks, numbers-first. Deep ops untuk operator yang udah scale.',
    tagline: '"Playbook Dari Operator Yang Masih Jalan. Closed-Door."',
    format: 'Tactical Add-On + Operator Guest',
    price: 'Rp 8.5 JT',
    accent: 'crimson',
    moduleCount: 12,
    structureLabel: '4 Cluster Tactical',
    groupNoun: 'Cluster',
  },
};

// Tag → color mapping used by module chips
export const TAG_COLOR = {
  fundamental:           { bg: 'rgba(200,131,12,.12)', c: '#9A5F08' },
  teknis:                { bg: 'rgba(30,58,138,.10)',  c: '#1E3A8A' },
  ops:                   { bg: 'rgba(122,44,44,.12)',  c: '#7A2C2C' },
  growth:                { bg: 'rgba(22,101,52,.10)',  c: '#166534' },
  framework:             { bg: 'rgba(200,131,12,.12)', c: '#9A5F08' },
  'case-study':          { bg: 'rgba(185,28,28,.10)',  c: '#B91C1C' },
  strategic:             { bg: 'rgba(30,58,138,.10)',  c: '#1E3A8A' },
  'ops-scaling':         { bg: 'rgba(122,44,44,.12)',  c: '#7A2C2C' },
  finance:               { bg: 'rgba(22,101,52,.10)',  c: '#166534' },
  team:                  { bg: 'rgba(91,58,75,.12)',   c: '#5B3A4B' },
  ads:                   { bg: 'rgba(200,131,12,.12)', c: '#9A5F08' },
  cpas:                  { bg: 'rgba(30,58,138,.10)',  c: '#1E3A8A' },
  'kol-360':             { bg: 'rgba(185,28,28,.10)',  c: '#B91C1C' },
  tactical:              { bg: 'rgba(185,28,28,.10)',  c: '#B91C1C' },
  affiliate:             { bg: 'rgba(185,28,28,.10)',  c: '#B91C1C' },
  'internal-team':       { bg: 'rgba(91,58,75,.12)',   c: '#5B3A4B' },
  clipper:               { bg: 'rgba(185,28,28,.10)',  c: '#B91C1C' },
  'content-multiplication': { bg: 'rgba(122,44,44,.12)', c: '#7A2C2C' },
  'grey-area':           { bg: 'rgba(154,95,8,.15)',   c: '#9A5F08' },
  'traffic-hacking':     { bg: 'rgba(185,28,28,.10)',  c: '#B91C1C' },
  viral:                 { bg: 'rgba(185,28,28,.10)',  c: '#B91C1C' },
  launch:                { bg: 'rgba(200,131,12,.12)', c: '#9A5F08' },
  lifecycle:             { bg: 'rgba(91,58,75,.12)',   c: '#5B3A4B' },
  'gmv-max':             { bg: 'rgba(185,28,28,.10)',  c: '#B91C1C' },
  'anti-boncos':         { bg: 'rgba(122,44,44,.12)',  c: '#7A2C2C' },
  shopee:                { bg: 'rgba(200,131,12,.12)', c: '#9A5F08' },
  attribution:           { bg: 'rgba(30,58,138,.10)',  c: '#1E3A8A' },
  live:                  { bg: 'rgba(30,58,138,.10)',  c: '#1E3A8A' },
  negotiation:           { bg: 'rgba(30,58,138,.10)',  c: '#1E3A8A' },
  'am-relationship':     { bg: 'rgba(91,58,75,.12)',   c: '#5B3A4B' },
  insider:               { bg: 'rgba(185,28,28,.10)',  c: '#B91C1C' },
};
